include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_relative_imports: true
    prefer_single_quotes: true
    use_build_context_synchronously: false
    library_private_types_in_public_api: false