name: discover_deep_cove
description: Guided walk application for visitors to Deep Cove.
# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.2.5+24

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  archive: ^2.0.8                     # Apache 2.0
  audioplayers: ^0.13.1               # MIT
  carousel_pro: ^1.0.0                # MIT
  cron: ^0.2.2                        # BSD
  flutter:
    sdk: flutter
  flutter_dotenv: ^2.0.1              # MIT
  flutter_icons: 1.0.0+1              # Apache 2.0
  flutter_launcher_icons: ^0.7.2+1    # MIT
  flutter_local_notifications: ^0.8.3 # BSD
  font_awesome_flutter: ^8.4.0        # MIT
  gallery_saver: ^1.0.4               # Apache 2.0
  http: ^0.12.0+2                     # BSD
  image_picker: ^0.6.0+15             # Apache 2.0
  majascan: 0.3.5                     # MIT
  path_provider: ^1.3.0               # BSD
  path_provider_ex: ^1.0.1            # MIT
  percent_indicator: ^2.1.1+1         # BSD
  permission_handler: ^3.0.1          # MIT
  shared_preferences: ^0.5.4+6        # BSD
  toast: ^0.1.4                       # MIT

  # Database related packages
  jaguar_orm: ^2.2.6                  # BSD
  jaguar_query_sqflite: ^2.2.9        # BSD
  sqflite: ^1.1.5                     # MIT

  # Map related packages
  flutter_map: ^0.5.6
  flutter_map_marker_cluster: ^0.2.1  # BSD

dev_dependencies:
  build_runner: ^1.1.0      #BSD    -   1.4.0 available but not supported by Jaguar at this time
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter  
  jaguar_orm_gen: ^2.2.27   #BSD

flutter_icons:
  android: "launcher_icon" 
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/icon/icon.png
    - assets/peaks.png
    - assets/map.mbtiles
    - assets/invalidQRcode.png
