name: discover_deep_cove
description: Guided walk application for visitors to Deep Cove.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  barcode_scan:
  flutter_map: ^0.5.5+2
  font_awesome_flutter: ^8.4.0
  audioplayers: ^0.11.0  
  carousel_pro: ^0.0.13
  flutter_launcher_icons: "^0.7.2"
  flutter_map_marker_cluster: ^0.2.0+1
  toast: ^0.1.3  
  image_picker: ^0.6.0+10

flutter_icons:
  android: "launcher_icon" 
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  assets:
  # util
  - assets/icon/icon.png
  - assets/peaks.png
  - assets/map.mbtiles
  - assets/logo.png

  ##FactFile
  # primary
  - assets/images/primary/kea.jpg
  - assets/images/primary/rifleman.jpg
  - assets/images/primary/tomtit.jpg
  - assets/images/primary/mountainBeech.jpg
  - assets/images/primary/rimu.jpg
  - assets/images/primary/pekinDuck.jpg
  - assets/images/primary/powerStation.jpg
  # secondary
  - assets/images/secondary/kea.jpg
  - assets/images/secondary/rifleman.jpg
  - assets/images/secondary/tomtit.jpg
  - assets/images/secondary/mountainBeech.jpg
  - assets/images/secondary/rimu.jpg
  - assets/images/secondary/pekinDuck.png
  - assets/images/secondary/powerStation.jpg
  #tertiary
  - assets/images/tertiary/kea.jpg
  - assets/images/tertiary/rifleman.jpg
  - assets/images/tertiary/tomtit.jpg
  - assets/images/tertiary/mountainBeech.jpg
  - assets/images/tertiary/rimu.jpg
  - assets/images/tertiary/pekinDuck.png
  - assets/images/tertiary/powerStation.jpg

  ##Activities
  #count
  - assets/images/activities/count/lancewood.jpg
  #pictureSelect
  - assets/images/activities/pictureSelect/mountainBeech.jpg
  - assets/images/activities/pictureSelect/rimu.jpg
  - assets/images/activities/pictureSelect/totara.jpg
  #pictureTap
  - assets/images/activities/pictureTap/powerStation.jpg
  #textAnswer
  - assets/images/activities/textAnswer/stump.jpg


  # Pronunciations
  - assets/audio/pronunciations/kea.mp3

  # Calls
  - assets/audio/calls/kea.mp3
##End Assets

  uses-material-design: true
