name: discover_deep_cove
description: Guided walk application for visitors to Deep Cove.
publish_to none:

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  archive: ^2.0.8                         # Apache 2.0
  audioplayers: ^0.17.4                   # MIT
  carousel_pro: ^1.0.0                    # MIT
  cron: ^0.5.0                            # BSD
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2                  # MIT
  flutter_icons: ^1.1.0                   # Apache 2.0
  flutter_launcher_icons: ^0.8.1          # MIT
  flutter_local_notifications: ^4.0.1+2   # BSD
  font_awesome_flutter: ^10.1.0           # MIT
  gallery_saver: ^2.0.3                   # Apache 2.0
  http: ^0.12.0+2                         # BSD
  image_picker: ^0.6.0+15                 # Apache 2.0
  majascan: ^0.5.0                        # MIT
  meta: ^1.7.0                            # BSD
  path: ^1.8.1                            # BSD
  path_provider: ^1.3.0                   # BSD
  path_provider_ex: ^1.0.1                # MIT
  percent_indicator: ^4.2.2               # BSD
  permission_handler: ^5.1.0+2 
  shared_preferences: ^0.5.4+6            # BSD
  toast: ^0.3.0                           # MIT

  # Database related packages
  jaguar_orm: ^2.2.6                      # BSD
  jaguar_query_sqflite: ^2.2.9            # BSD
  sqflite: ^1.1.5                         # MIT

  # Map related packages
  flutter_map: ^0.12.0                    # BSD
  flutter_map_marker_cluster: ^0.3.5      # BSD
  flutter_map_mbtiles_provider:
    path: ./flutter_map_mbtiles_provider

dependency_overrides:
  platform: ^3.1.0                        # BSD

dev_dependencies:
  build_runner: ^1.1.0                    # BSD    -   1.4.0 available but not supported by Jaguar at this time
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter  
  jaguar_orm_gen: ^2.2.27                 # BSD

flutter_icons:
  android: "launcher_icon" 
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/icon/icon.png
    - assets/peaks.png
    - assets/map.mbtiles
    - assets/invalidQRcode.png
